# Generated by Django 4.2 on 2023-06-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_alter_item_price_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='reviews/uploads/', verbose_name='Add an Image'),
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/uploads', verbose_name='Upload an image')),
                ('default', models.BooleanField(default=False, verbose_name='Use as main image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product', verbose_name='Product')),
            ],
        ),
    ]
