# Generated by Django 4.2 on 2023-06-11 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0003_alter_review_image_rename_item_product_itemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_number', models.PositiveIntegerField(verbose_name='Department Name')),
                ('department_address', models.TextField(verbose_name='Department Address')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Shipping Company Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=25, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items/uploads', verbose_name='Upload an Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(verbose_name='Number in Stock'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=25, verbose_name='Subcategory Name'),
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.city', verbose_name='City')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.department', verbose_name='Shipping Department')),
                ('ship_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.shippingcompany', verbose_name='Ship via')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='reviews/uploads', verbose_name='Upload an Image')),
                ('default', models.BooleanField(default=False, verbose_name='Use as main image')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.review', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.shippingcompany', verbose_name='Shipping Company'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.country', verbose_name='Country'),
        ),
    ]
