# Generated by Django 4.2 on 2023-06-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_city_country_department_shippingcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.city'),
        ),
    ]
