# Generated by Django 4.2 on 2023-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_alter_itemimage_image_alter_reviewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items/uploads', verbose_name='Upload an Image'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(null=True, upload_to='reviews/uploads', verbose_name='Upload an Image'),
        ),
    ]
