# Generated by Django 4.2 on 2023-06-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_remove_cart_order_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
